### ISSUE TITLE
STRG + F3 sets the sound volume to 100% when you disable and enable it ingame

### ISSUE THREAD

**Issue by Danghorx** [legacyclonk/LegacyClonk#113] opened 2023-11-04 10:13 UTC
It should keep the volume that you had previously before you muted the sound.

**Comment by maxmitti** [comment] 2023-11-19 18:26
Please explain in more detail which volume setting you mean (Global sound volume in options / volume specified in Sound() function, etc.).
And please describe a setup which makes it easy to reproduce and notice.

**Comment by Danghorx** [comment] 2023-11-19 19:11
![clonk_E1VLTb0cox](https://github.com/legacyclonk/LegacyClonk/assets/89202978/a164cbfa-8b57-4257-9e0f-1da9b3e0d88b)
That one jumped to 100% from 50%.
I played KdG and near the end of a round i tested it because there were noisy sounds. The sounds were louder after i enabled it again ingame. After that i checked in the options and it was at 100% Sound in the options.

I havent been able to reproduce this after that round.

**Comment by maxmitti** [comment] 2024-03-28 16:56
I am closing it, since it is not reproducible.
Just reopen it, should you notice it again.

**Closed by maxmitti** 2024-03-28 16:56 UTC
Labels: bug, gui
